### ISSUE TITLE
Infer doesn't treat 'sizeof' expressions as constants

### ISSUE THREAD

**Issue by vsilyaev** [facebook/infer#706]
Infer version v0.13.0-8fde270
It appears infer doesn't treat 'sizeof' expressions as constants, and generally doesn't reduce sizeof  expressions.
```
$infer --version
Infer version v0.13.0-8fde270
Copyright 2009 - present Facebook. All Rights Reserved.
```
```C
$cat >test.c <<EOF
int test(void)
{
    int a=4;
    int b=sizeof(a);
    char c[2];

    if(a%4) { return a/0; }
    if(b%sizeof(a)) { return a/0; }
    if(sizeof(c)>4) { return a/0; }
    if( (sizeof(c)/sizeof(c[0])) != 2) {return a/0; }
    return 0;
}
EOF
```
```
$infer --no-filtering -- cc -c test.c
Capturing in make/cc mode...
Found 1 source file to analyze in /tmp/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F.

Found 3 issues

test.c:10: error: DIVIDE_BY_ZERO
  Expression `0` could be zero at line 10, column 41.
  8.       if(b%sizeof(a)) { return a/0; }
  9.       if(sizeof(c)>4) { return a/0; }
  10. >     if( (sizeof(c)/sizeof(c[0])) != 2) {return a/0; }
  11.       return 0;
  12.   }

test.c:8: error: DIVIDE_BY_ZERO
  Expression `0` could be zero at line 8, column 23.
  6.
  7.       if(a%4) { return a/0; }
  8. >     if(b%sizeof(a)) { return a/0; }
  9.       if(sizeof(c)>4) { return a/0; }
  10.       if( (sizeof(c)/sizeof(c[0])) != 2) {return a/0; }

test.c:9: error: DIVIDE_BY_ZERO
  Expression `0` could be zero at line 9, column 23.
  7.       if(a%4) { return a/0; }
  8.       if(b%sizeof(a)) { return a/0; }
  9. >     if(sizeof(c)>4) { return a/0; }
  10.       if( (sizeof(c)/sizeof(c[0])) != 2) {return a/0; }
  11.       return 0;


Summary of the reports

  DIVIDE_BY_ZERO: 3
```

**Comment by jvillard** [comment]
Thanks for the detailed report. I'll look into it.

**Comment by jvillard** [comment]
Thanks again for the report @vsilyaev, I believe it should be fixed in master now.

**Comment by vsilyaev** [comment]
Yes,  b2ee115 in master resolves all issues from the posted snippet, however there is some peculiar case that still exists:
```
$infer --version
Infer version v0.13.0-d850492
Copyright 2009 - present Facebook. All Rights Reserved.
$cat >test.c <<EOF
void test(void)
{
    char a[16];
    int b[16];
    unsigned i;

    a[15]=0;
    a[sizeof(a)-1]=0;
    b[sizeof(a)/sizeof(a)-1]=0;
    a[sizeof(a)/sizeof(*a)-1]=0;
    b[15]=0;
    b[sizeof(b)/sizeof(*b)-1]=0;
    for(i=0;i<sizeof(a);i++) {
        a[i]=0;
    }
    for(i=0;i<sizeof(a)/sizeof(a[0]);i++) {
        a[i] = 0;
    }
    for(i=0;i<sizeof(b)/sizeof(b[0]);i++) {
        b[i] = 0;
    }
}
EOF
$infer --no-filtering -- cc -c test.c
Capturing in make/cc mode...
Found 1 source file to analyze in /tmp/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F.

Found 2 issues

test.c:12: warning: ARRAY_OUT_OF_BOUNDS_L2
  array `b` `of size 16` could be accessed with an index out of bounds at line 12, column 5.
  10.       a[sizeof(a)/sizeof(*a)-1]=0;
  11.       b[15]=0;
  12. >     b[sizeof(b)/sizeof(*b)-1]=0;
  13.       for(i=0;i<sizeof(a);i++) {
  14.           a[i]=0;

test.c:10: warning: ARRAY_OUT_OF_BOUNDS_L2
  array `a` `of size 16` could be accessed with an index out of bounds at line 10, column 5.
  8.       a[sizeof(a)-1]=0;
  9.       b[sizeof(a)/sizeof(a)-1]=0;
  10. >     a[sizeof(a)/sizeof(*a)-1]=0;
  11.       b[15]=0;
  12.       b[sizeof(b)/sizeof(*b)-1]=0;


Summary of the reports

  ARRAY_OUT_OF_BOUNDS_L2: 2
```

P.S. Snippet also includes  many important cases that are resolved properly.
