### ISSUE TITLE
Null dereference analysis (for C) fails to see through malloc'd pointer

### ISSUE THREAD

**Issue by iphydf** [facebook/infer#869]
```c
#include <stdlib.h>

typedef struct Foo {
  int *i;
} Foo;

void foo(void) {
  Foo *f = malloc(sizeof *f);
  if (!f) {
    return 0;
  }

  f->i = malloc(sizeof(int));

  if (!f->i) {
    *f->i = 0; // BOOM! (but no error)
  }

  free(f->i);
  free(f);
}
```

Changing it to the following:
```c
#include <stdlib.h>

typedef struct Foo {
  int *i;
} Foo;

void foo(void) {
  Foo o;
  Foo *f = &o;
  if (!f) {
    return 0;
  }

  f->i = malloc(sizeof(int));

  if (!f->i) {
    *f->i = 0;
  }

  free(f->i);
}
```

Yields:
```
Found 1 issue

testcase.c:17: error: NULL_DEREFERENCE
  pointer `f->i` last assigned on line 14 could be null and is dereferenced at line 17, column 5.
  15.
  16.     if (!f->i) {
  17. >     *f->i = 0;
  18.     }
  19.
```

**Comment by da319** [comment]
Thanks for the report!

Infer does not understand `sizeof *f` in `Foo *f = malloc(sizeof *f)`. It does find NULL reference, if you change `sizeof *f` to `sizeof (Foo)`. 

I am working on adding a support for `sizeof expression`.

**Comment by da319** [comment]
This should be fixed now. Thanks again for the report.

**Comment by PatriciaSVMonteiro** [comment]
I just downloaded the last version and it seems that this bug is still present.  Do you confirm? Thanks.

**Comment by da319** [comment]
Could you let me know what bug do you have in mind and which version of infer do you use? 

Now infer supports `sizeof expression` and the NULL_DEREFERENCE is reported in both of the above examples.

**Comment by PatriciaSVMonteiro** [comment]
I was using version v0.13.1 and I just realized that version v0.14.0 was released. I've been trying to install it, but to no success so far. Is installation / upgrade via brew still viable?

**Comment by TomMD** [comment]
It appears to be fixed.  Using a recent infer:

```
% infer run -- gcc -c xx.c
Capturing in make/cc mode...
Found 1 source file to analyze in /tmp/infer-out
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

F.

Found 1 issue

xx.c:16: error: NULL_DEREFERENCE
  pointer `f->i` last assigned on line 13 could be null and is dereferenced at line 16, column 5.
  14.
  15.     if (!f->i) {
  16. >     *f->i = 0; // BOOM! (but no error)
  17.     }
  18.


Summary of the reports

  NULL_DEREFERENCE: 1
tommd@ubuntu1604-xenial /tmp% infer --version
Infer version v0.14.0-0bbdf63
Copyright 2009 - present Facebook. All Rights Reserved.
```
